# Site settings
name: Jumpcue
description: Styptic observations about product and tech, character assassinations both real and imagined, irrational perspectivism
url: http://jumpcue.co
title: jumpcue.co
email: hi@jumpcue.co
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jumpcue.co" # the base hostname & protocol for your site
twitter_username: jumpcueco

# Build settings
markdown: kramdown
